@startuml USP_Components
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

' Define container boundary
Container_Boundary(c2WebUi, "Ultimate StarPlan Web UI") {
  Component(timetableView, "TimetableView", "React Component", "Allows users to show their timetable")
  Component(configuratorView, "ConfiguratorView", "React Component", "Lets users generate custom timetables")
}

' External actors
Person(student, "Student", "Uses StarPlan to plan their semester")

' Containers
Container(service, "Service", "React Component", "Provides timetable and room data")

' Relationships
Rel(student, timetableView, "Views timetable via")
Rel(student, configuratorView, "Generates custom plan via")

Rel(timetableView, service, "Uses data from")
Rel(configuratorView, service, "Uses data from")

@enduml
